export const locations = [
    { city: "Wrocław", voivodeship: "Dolnośląskie" },
{ city: "Wałbrzych", voivodeship: "Dolnośląskie" },
{ city: "Legnica", voivodeship: "Dolnośląskie" },
{ city: "Jelenia Góra", voivodeship: "Dolnośląskie" },
{ city: "Lubin", voivodeship: "Dolnośląskie" },
{ city: "Głogów", voivodeship: "Dolnośląskie" },
{ city: "Świdnica", voivodeship: "Dolnośląskie" },
{ city: "Bolesławiec", voivodeship: "Dolnośląskie" },
{ city: "Oleśnica", voivodeship: "Dolnośląskie" },
{ city: "Dzierżoniów", voivodeship: "Dolnośląskie" },
{ city: "Bielawa", voivodeship: "Dolnośląskie" },
{ city: "Oława", voivodeship: "Dolnośląskie" },
{ city: "Zgorzelec", voivodeship: "Dolnośląskie" },
{ city: "Świebodzice", voivodeship: "Dolnośląskie" },
{ city: "Strzegom", voivodeship: "Dolnośląskie" },
{ city: "Lubawka", voivodeship: "Dolnośląskie" },
{ city: "Trzebnica", voivodeship: "Dolnośląskie" },
{ city: "Jawor", voivodeship: "Dolnośląskie" },
{ city: "Nowa Ruda", voivodeship: "Dolnośląskie" },
{ city: "Polkowice", voivodeship: "Dolnośląskie" },
{ city: "Kamienna Góra", voivodeship: "Dolnośląskie" },
{ city: "Lubań", voivodeship: "Dolnośląskie" },
{ city: "Ząbkowice Śląskie", voivodeship: "Dolnośląskie" },
{ city: "Kłodzko", voivodeship: "Dolnośląskie" },
{ city: "Środa Śląska", voivodeship: "Dolnośląskie" },
{ city: "Chojnów", voivodeship: "Dolnośląskie" },
{ city: "Góra", voivodeship: "Dolnośląskie" },
{ city: "Milicz", voivodeship: "Dolnośląskie" },
{ city: "Wołów", voivodeship: "Dolnośląskie" },
{ city: "Kowary", voivodeship: "Dolnośląskie" },
{ city: "Strzelin", voivodeship: "Dolnośląskie" },
{ city: "Złotoryja", voivodeship: "Dolnośląskie" },
{ city: "Lwówek Śląski", voivodeship: "Dolnośląskie" },
{ city: "Bogatynia", voivodeship: "Dolnośląskie" },
{ city: "Jelcz-Laskowice", voivodeship: "Dolnośląskie" },
{ city: "Ścinawa", voivodeship: "Dolnośląskie" },
{ city: "Pieńsk", voivodeship: "Dolnośląskie" },
{ city: "Chocianów", voivodeship: "Dolnośląskie" },
{ city: "Syców", voivodeship: "Dolnośląskie" },
{ city: "Prusice", voivodeship: "Dolnośląskie" },
{ city: "Prochowice", voivodeship: "Dolnośląskie" },
{ city: "Węgliniec", voivodeship: "Dolnośląskie" },
{ city: "Ziębice", voivodeship: "Dolnośląskie" },
{ city: "Niemcza", voivodeship: "Dolnośląskie" },
{ city: "Bystrzyca Kłodzka", voivodeship: "Dolnośląskie" },
{ city: "Leśna", voivodeship: "Dolnośląskie" },
{ city: "Mirsk", voivodeship: "Dolnośląskie" },
{ city: "Radków", voivodeship: "Dolnośląskie" },
{ city: "Międzylesie", voivodeship: "Dolnośląskie" },
{ city: "Bydgoszcz", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Toruń", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Włocławek", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Grudziądz", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Inowrocław", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Brodnica", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Świecie", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Chełmno", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Nakło nad Notecią", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Rypin", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Solec Kujawski", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Aleksandrów Kujawski", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Chełmża", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Żnin", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Ciechocinek", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Lipno", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Tuchola", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Mogilno", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Koronowo", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Radziejów", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Janikowo", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Łabiszyn", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Barcin", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Sępólno Krajeńskie", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Gniewkowo", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Więcbork", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Nowe", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Skępe", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Golub-Dobrzyń", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Kamień Krajeński", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Brześć Kujawski", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Lubraniec", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Kruszwica", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Jabłonowo Pomorskie", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Mrocza", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Chodecz", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Kcynia", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Nieszawa", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Pruszcz", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Strzelno", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Szubin", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Jastrowie", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Górzno", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Białe Błota", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Solec nad Wisłą", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Lisewo", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Gąsawa", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Rogowo", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Fabianki", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Sadki", voivodeship: "Kujawsko-Pomorskie" },
{ city: "Lublin", voivodeship: "Lubelskie" },
{ city: "Chełm", voivodeship: "Lubelskie" },
{ city: "Zamość", voivodeship: "Lubelskie" },
{ city: "Biała Podlaska", voivodeship: "Lubelskie" },
{ city: "Puławy", voivodeship: "Lubelskie" },
{ city: "Świdnik", voivodeship: "Lubelskie" },
{ city: "Kraśnik", voivodeship: "Lubelskie" },
{ city: "Łuków", voivodeship: "Lubelskie" },
{ city: "Krasnystaw", voivodeship: "Lubelskie" },
{ city: "Biłgoraj", voivodeship: "Lubelskie" },
{ city: "Lubartów", voivodeship: "Lubelskie" },
{ city: "Tomaszów Lubelski", voivodeship: "Lubelskie" },
{ city: "Hrubieszów", voivodeship: "Lubelskie" },
{ city: "Radzyń Podlaski", voivodeship: "Lubelskie" },
{ city: "Parczew", voivodeship: "Lubelskie" },
{ city: "Opole Lubelskie", voivodeship: "Lubelskie" },
{ city: "Ryki", voivodeship: "Lubelskie" },
{ city: "Łęczna", voivodeship: "Lubelskie" },
{ city: "Janów Lubelski", voivodeship: "Lubelskie" },
{ city: "Włodawa", voivodeship: "Lubelskie" },
{ city: "Międzyrzec Podlaski", voivodeship: "Lubelskie" },
{ city: "Bełżyce", voivodeship: "Lubelskie" },
{ city: "Szczebrzeszyn", voivodeship: "Lubelskie" },
{ city: "Frampol", voivodeship: "Lubelskie" },
{ city: "Rejowiec", voivodeship: "Lubelskie" },
{ city: "Rejowiec Fabryczny", voivodeship: "Lubelskie" },
{ city: "Tyszowce", voivodeship: "Lubelskie" },
{ city: "Kazimierz Dolny", voivodeship: "Lubelskie" },
{ city: "Ostrów Lubelski", voivodeship: "Lubelskie" },
{ city: "Annopol", voivodeship: "Lubelskie" },
{ city: "Nałęczów", voivodeship: "Lubelskie" },
{ city: "Poniatowa", voivodeship: "Lubelskie" },
{ city: "Bychawa", voivodeship: "Lubelskie" },
{ city: "Dęblin", voivodeship: "Lubelskie" },
{ city: "Modliborzyce", voivodeship: "Lubelskie" },
{ city: "Łaszczów", voivodeship: "Lubelskie" },
{ city: "Piaski", voivodeship: "Lubelskie" },
{ city: "Terespol", voivodeship: "Lubelskie" },
{ city: "Józefów", voivodeship: "Lubelskie" },
{ city: "Urzedów", voivodeship: "Lubelskie" },
{ city: "Ostrowiec", voivodeship: "Lubelskie" },
{ city: "Kock", voivodeship: "Lubelskie" },
{ city: "Siedliszcze", voivodeship: "Lubelskie" },
{ city: "Kozienice", voivodeship: "Lubelskie" },
{ city: "Łukowa", voivodeship: "Lubelskie" },
{ city: "Lubycza Królewska", voivodeship: "Lubelskie" },
{ city: "Sławatycze", voivodeship: "Lubelskie" },
{ city: "Tarnogród", voivodeship: "Lubelskie" },
{ city: "Wojciechów", voivodeship: "Lubelskie" },
{ city: "Łódź", voivodeship: "Łódzkie" },
{ city: "Piotrków Trybunalski", voivodeship: "Łódzkie" },
{ city: "Pabianice", voivodeship: "Łódzkie" },
{ city: "Tomaszów Mazowiecki", voivodeship: "Łódzkie" },
{ city: "Bełchatów", voivodeship: "Łódzkie" },
{ city: "Zgierz", voivodeship: "Łódzkie" },
{ city: "Radomsko", voivodeship: "Łódzkie" },
{ city: "Skierniewice", voivodeship: "Łódzkie" },
{ city: "Kutno", voivodeship: "Łódzkie" },
{ city: "Sieradz", voivodeship: "Łódzkie" },
{ city: "Łowicz", voivodeship: "Łódzkie" },
{ city: "Opoczno", voivodeship: "Łódzkie" },
{ city: "Zduńska Wola", voivodeship: "Łódzkie" },
{ city: "Łęczyca", voivodeship: "Łódzkie" },
{ city: "Ozorków", voivodeship: "Łódzkie" },
{ city: "Rawa Mazowiecka", voivodeship: "Łódzkie" },
{ city: "Koluszki", voivodeship: "Łódzkie" },
{ city: "Poddębice", voivodeship: "Łódzkie" },
{ city: "Łask", voivodeship: "Łódzkie" },
{ city: "Wieluń", voivodeship: "Łódzkie" },
{ city: "Brzeziny", voivodeship: "Łódzkie" },
{ city: "Konstantynów Łódzki", voivodeship: "Łódzkie" },
{ city: "Głowno", voivodeship: "Łódzkie" },
{ city: "Wieruszów", voivodeship: "Łódzkie" },
{ city: "Aleksandrów Łódzki", voivodeship: "Łódzkie" },
{ city: "Działoszyn", voivodeship: "Łódzkie" },
{ city: "Pajęczno", voivodeship: "Łódzkie" },
{ city: "Uniejów", voivodeship: "Łódzkie" },
{ city: "Warta", voivodeship: "Łódzkie" },
{ city: "Stryków", voivodeship: "Łódzkie" },
{ city: "Sulejów", voivodeship: "Łódzkie" },
{ city: "Biała Rawska", voivodeship: "Łódzkie" },
{ city: "Drzewica", voivodeship: "Łódzkie" },
{ city: "Wolbórz", voivodeship: "Łódzkie" },
{ city: "Żychlin", voivodeship: "Łódzkie" },
{ city: "Tuszyn", voivodeship: "Łódzkie" },
{ city: "Zelów", voivodeship: "Łódzkie" },
{ city: "Błaszki", voivodeship: "Łódzkie" },
{ city: "Przedbórz", voivodeship: "Łódzkie" },
{ city: "Sędziejowice", voivodeship: "Łódzkie" },
{ city: "Żelechlinek", voivodeship: "Łódzkie" },
{ city: "Dalików", voivodeship: "Łódzkie" },
{ city: "Gomunice", voivodeship: "Łódzkie" },
{ city: "Gidle", voivodeship: "Łódzkie" },
{ city: "Ksawerów", voivodeship: "Łódzkie" },
{ city: "Parzęczew", voivodeship: "Łódzkie" },
{ city: "Piątek", voivodeship: "Łódzkie" },
{ city: "Sławno", voivodeship: "Łódzkie" },
{ city: "Zadzim", voivodeship: "Łódzkie" },
{ city: "Kraków", voivodeship: "Małopolskie" },
{ city: "Tarnów", voivodeship: "Małopolskie" },
{ city: "Nowy Sącz", voivodeship: "Małopolskie" },
{ city: "Oświęcim", voivodeship: "Małopolskie" },
{ city: "Chrzanów", voivodeship: "Małopolskie" },
{ city: "Nowy Targ", voivodeship: "Małopolskie" },
{ city: "Bochnia", voivodeship: "Małopolskie" },
{ city: "Andrychów", voivodeship: "Małopolskie" },
{ city: "Kęty", voivodeship: "Małopolskie" },
{ city: "Wieliczka", voivodeship: "Małopolskie" },
{ city: "Gorlice", voivodeship: "Małopolskie" },
{ city: "Brzesko", voivodeship: "Małopolskie" },
{ city: "Myślenice", voivodeship: "Małopolskie" },
{ city: "Trzebinia", voivodeship: "Małopolskie" },
{ city: "Limanowa", voivodeship: "Małopolskie" },
{ city: "Zakopane", voivodeship: "Małopolskie" },
{ city: "Olkusz", voivodeship: "Małopolskie" },
{ city: "Skawina", voivodeship: "Małopolskie" },
{ city: "Wadowice", voivodeship: "Małopolskie" },
{ city: "Libiąż", voivodeship: "Małopolskie" },
{ city: "Stary Sącz", voivodeship: "Małopolskie" },
{ city: "Miechów", voivodeship: "Małopolskie" },
{ city: "Proszowice", voivodeship: "Małopolskie" },
{ city: "Dąbrowa Tarnowska", voivodeship: "Małopolskie" },
{ city: "Sucha Beskidzka", voivodeship: "Małopolskie" },
{ city: "Krzeszowice", voivodeship: "Małopolskie" },
{ city: "Niepołomice", voivodeship: "Małopolskie" },
{ city: "Skała", voivodeship: "Małopolskie" },
{ city: "Maków Podhalański", voivodeship: "Małopolskie" },
{ city: "Słomniki", voivodeship: "Małopolskie" },
{ city: "Sułkowice", voivodeship: "Małopolskie" },
{ city: "Nowy Wiśnicz", voivodeship: "Małopolskie" },
{ city: "Biecz", voivodeship: "Małopolskie" },
{ city: "Piwniczna-Zdrój", voivodeship: "Małopolskie" },
{ city: "Bobowa", voivodeship: "Małopolskie" },
{ city: "Rabka-Zdrój", voivodeship: "Małopolskie" },
{ city: "Jordanów", voivodeship: "Małopolskie" },
{ city: "Szczawnica", voivodeship: "Małopolskie" },
{ city: "Zator", voivodeship: "Małopolskie" },
{ city: "Tuchów", voivodeship: "Małopolskie" },
{ city: "Kalwaria Zebrzydowska", voivodeship: "Małopolskie" },
{ city: "Radłów", voivodeship: "Małopolskie" },
{ city: "Ciężkowice", voivodeship: "Małopolskie" },
{ city: "Wojnicz", voivodeship: "Małopolskie" },
{ city: "Dobczyce", voivodeship: "Małopolskie" },
{ city: "Koszyce", voivodeship: "Małopolskie" },
{ city: "Tymbark", voivodeship: "Małopolskie" },
{ city: "Nowe Brzesko", voivodeship: "Małopolskie" },
{ city: "Łososina Dolna", voivodeship: "Małopolskie" },
{ city: "Łapanów", voivodeship: "Małopolskie" },
{ city: "Warszawa", voivodeship: "Mazowieckie" },
{ city: "Radom", voivodeship: "Mazowieckie" },
{ city: "Płock", voivodeship: "Mazowieckie" },
{ city: "Siedlce", voivodeship: "Mazowieckie" },
{ city: "Pruszków", voivodeship: "Mazowieckie" },
{ city: "Ostrołęka", voivodeship: "Mazowieckie" },
{ city: "Legionowo", voivodeship: "Mazowieckie" },
{ city: "Piaseczno", voivodeship: "Mazowieckie" },
{ city: "Otwock", voivodeship: "Mazowieckie" },
{ city: "Żyrardów", voivodeship: "Mazowieckie" },
{ city: "Marek", voivodeship: "Mazowieckie" },
{ city: "Sochaczew", voivodeship: "Mazowieckie" },
{ city: "Wołomin", voivodeship: "Mazowieckie" },
{ city: "Ząbki", voivodeship: "Mazowieckie" },
{ city: "Grodzisk Mazowiecki", voivodeship: "Mazowieckie" },
{ city: "Ciechanów", voivodeship: "Mazowieckie" },
{ city: "Piastów", voivodeship: "Mazowieckie" },
{ city: "Płońsk", voivodeship: "Mazowieckie" },
{ city: "Milanówek", voivodeship: "Mazowieckie" },
{ city: "Błonie", voivodeship: "Mazowieckie" },
{ city: "Konstancin-Jeziorna", voivodeship: "Mazowieckie" },
{ city: "Łomianki", voivodeship: "Mazowieckie" },
{ city: "Mińsk Mazowiecki", voivodeship: "Mazowieckie" },
{ city: "Góra Kalwaria", voivodeship: "Mazowieckie" },
{ city: "Nowy Dwór Mazowiecki", voivodeship: "Mazowieckie" },
{ city: "Sulejówek", voivodeship: "Mazowieckie" },
{ city: "Zielonka", voivodeship: "Mazowieckie" },
{ city: "Wyszków", voivodeship: "Mazowieckie" },
{ city: "Żuromin", voivodeship: "Mazowieckie" },
{ city: "Warka", voivodeship: "Mazowieckie" },
{ city: "Józefów", voivodeship: "Mazowieckie" },
{ city: "Sierpc", voivodeship: "Mazowieckie" },
{ city: "Kobyłka", voivodeship: "Mazowieckie" },
{ city: "Pionki", voivodeship: "Mazowieckie" },
{ city: "Przasnysz", voivodeship: "Mazowieckie" },
{ city: "Nasielsk", voivodeship: "Mazowieckie" },
{ city: "Mława", voivodeship: "Mazowieckie" },
{ city: "Kozienice", voivodeship: "Mazowieckie" },
{ city: "Ostrów Mazowiecka", voivodeship: "Mazowieckie" },
{ city: "Garwolin", voivodeship: "Mazowieckie" },
{ city: "Pułtusk", voivodeship: "Mazowieckie" },
{ city: "Grójec", voivodeship: "Mazowieckie" },
{ city: "Karczew", voivodeship: "Mazowieckie" },
{ city: "Łosice", voivodeship: "Mazowieckie" },
{ city: "Gostynin", voivodeship: "Mazowieckie" },
{ city: "Radzymin", voivodeship: "Mazowieckie" },
{ city: "Szydłowiec", voivodeship: "Mazowieckie" },
{ city: "Tarczyn", voivodeship: "Mazowieckie" },
{ city: "Gąbin", voivodeship: "Mazowieckie" },
{ city: "Bieżuń", voivodeship: "Mazowieckie" },
{ city: "Opole", voivodeship: "Opolskie" },
{ city: "Kędzierzyn-Koźle", voivodeship: "Opolskie" },
{ city: "Nysa", voivodeship: "Opolskie" },
{ city: "Brzeg", voivodeship: "Opolskie" },
{ city: "Krapkowice", voivodeship: "Opolskie" },
{ city: "Strzelce Opolskie", voivodeship: "Opolskie" },
{ city: "Kluczbork", voivodeship: "Opolskie" },
{ city: "Głubczyce", voivodeship: "Opolskie" },
{ city: "Prudnik", voivodeship: "Opolskie" },
{ city: "Ozimek", voivodeship: "Opolskie" },
{ city: "Bieruń", voivodeship: "Opolskie" },
{ city: "Głuchołazy", voivodeship: "Opolskie" },
{ city: "Łambinowice", voivodeship: "Opolskie" },
{ city: "Strzeleczki", voivodeship: "Opolskie" },
{ city: "Gogolin", voivodeship: "Opolskie" },
{ city: "Prószków", voivodeship: "Opolskie" },
{ city: "Otmuchów", voivodeship: "Opolskie" },
{ city: "Tarnów Opolski", voivodeship: "Opolskie" },
{ city: "Paczków", voivodeship: "Opolskie" },
{ city: "Chrząstowice", voivodeship: "Opolskie" },
{ city: "Turawa", voivodeship: "Opolskie" },
{ city: "Pokój", voivodeship: "Opolskie" },
{ city: "Gorzów Śląski", voivodeship: "Opolskie" },
{ city: "Skarbimierz", voivodeship: "Opolskie" },
{ city: "Leśnica", voivodeship: "Opolskie" },
{ city: "Zdzieszowice", voivodeship: "Opolskie" },
{ city: "Byczyna", voivodeship: "Opolskie" },
{ city: "Radłów", voivodeship: "Opolskie" },
{ city: "Dobrodzień", voivodeship: "Opolskie" },
{ city: "Kolonowskie", voivodeship: "Opolskie" },
{ city: "Łubniany", voivodeship: "Opolskie" },
{ city: "Praszka", voivodeship: "Opolskie" },
{ city: "Kietrz", voivodeship: "Opolskie" },
{ city: "Olesno", voivodeship: "Opolskie" },
{ city: "Twardogóra", voivodeship: "Opolskie" },
{ city: "Strzelce Małe", voivodeship: "Opolskie" },
{ city: "Olszanka", voivodeship: "Opolskie" },
{ city: "Prochowice", voivodeship: "Opolskie" },
{ city: "Popielów", voivodeship: "Opolskie" },
{ city: "Prudziszki", voivodeship: "Opolskie" },
{ city: "Dębica", voivodeship: "Opolskie" },
{ city: "Korfantów", voivodeship: "Opolskie" },
{ city: "Biała", voivodeship: "Opolskie" },
{ city: "Łosiów", voivodeship: "Opolskie" },
{ city: "Żelazno", voivodeship: "Opolskie" },
{ city: "Pilchowice", voivodeship: "Opolskie" },
{ city: "Grodziec", voivodeship: "Opolskie" },
{ city: "Dobieszowice", voivodeship: "Opolskie" },
{ city: "Szymiszów", voivodeship: "Opolskie" },
{city: "Rzeszów", voivodeship: "Podkarpackie"},
{city: "Stalowa Wola", voivodeship: "Podkarpackie"},
{city: "Przemyśl", voivodeship: "Podkarpackie"},
{city: "Tarnobrzeg", voivodeship: "Podkarpackie"},
{city: "Mielec", voivodeship: "Podkarpackie"},
{city: "Jarosław", voivodeship: "Podkarpackie"},
{city: "Sanok", voivodeship: "Podkarpackie"},
{city: "Dębica", voivodeship: "Podkarpackie"},
{city: "Nisko", voivodeship: "Podkarpackie"},
{city: "Ropczyce", voivodeship: "Podkarpackie"},
{city: "Łańcut", voivodeship: "Podkarpackie"},
{city: "Leżajsk", voivodeship: "Podkarpackie"},
{city: "Przeworsk", voivodeship: "Podkarpackie"},
{city: "Dynów", voivodeship: "Podkarpackie"},
{city: "Brzozów", voivodeship: "Podkarpackie"},
{city: "Rudnik nad Sanem", voivodeship: "Podkarpackie"},
{city: "Lesko", voivodeship: "Podkarpackie"},
{city: "Strzyżów", voivodeship: "Podkarpackie"},
{city: "Radomyśl Wielki", voivodeship: "Podkarpackie"},
{city: "Nowa Dęba", voivodeship: "Podkarpackie"},
{city: "Oleszyce", voivodeship: "Podkarpackie"},
{city: "Gorlice", voivodeship: "Podkarpackie"},
{city: "Krosno", voivodeship: "Podkarpackie"},
{city: "Kańczuga", voivodeship: "Podkarpackie"},
{city: "Jasło", voivodeship: "Podkarpackie"},
{city: "Radomysl nad Sanem", voivodeship: "Podkarpackie"},
{city: "Kolbuszowa", voivodeship: "Podkarpackie"},
{city: "Sędziszów Małopolski", voivodeship: "Podkarpackie"},
{city: "Lubaczów", voivodeship: "Podkarpackie"},
{city: "Głogów Małopolski", voivodeship: "Podkarpackie"},
{city: "Nowa Sarzyna", voivodeship: "Podkarpackie"},
{city: "Rymanów", voivodeship: "Podkarpackie"},
{city: "Żurawica", voivodeship: "Podkarpackie"},
{city: "Tyczyn", voivodeship: "Podkarpackie"},
{city: "Sokal", voivodeship: "Podkarpackie"},
{city: "Sieniawa", voivodeship: "Podkarpackie"},
{city: "Radymno", voivodeship: "Podkarpackie"},
{city: "Radomyśl nad Sanem", voivodeship: "Podkarpackie"},
{city: "Pruchnik", voivodeship: "Podkarpackie"},
{city: "Białystok", voivodeship: "Podlaskie"},
{city: "Łomża", voivodeship: "Podlaskie"},
{city: "Suwałki", voivodeship: "Podlaskie"},
{city: "Augustów", voivodeship: "Podlaskie"},
{city: "Bielsk Podlaski", voivodeship: "Podlaskie"},
{city: "Zambrów", voivodeship: "Podlaskie"},
{city: "Hajnówka", voivodeship: "Podlaskie"},
{city: "Grajewo", voivodeship: "Podlaskie"},
{city: "Łapy", voivodeship: "Podlaskie"},
{city: "Siemiatycze", voivodeship: "Podlaskie"},
{city: "Wysokie Mazowieckie", voivodeship: "Podlaskie"},
{city: "Tykocin", voivodeship: "Podlaskie"},
{city: "Wasilków", voivodeship: "Podlaskie"},
{city: "Grodno", voivodeship: "Podlaskie"},
{city: "Jaworzno", voivodeship: "Podkarpackie"},
{city: "Mońki", voivodeship: "Podlaskie"},
{city: "Zabłudów", voivodeship: "Podlaskie"},
{city: "Juchnowiec Kościelny", voivodeship: "Podlaskie"},
{city: "Brańsk", voivodeship: "Podlaskie"},
{city: "Goniądz", voivodeship: "Podlaskie"},
{city: "Czyżew", voivodeship: "Podlaskie"},
{city: "Sokółka", voivodeship: "Podlaskie"},
{city: "Knyszyn", voivodeship: "Podlaskie"},
{city: "Szepietowo", voivodeship: "Podlaskie"},
{city: "Rajgród", voivodeship: "Podlaskie"},
{city: "Suraż", voivodeship: "Podlaskie"},
{city: "Choroszcz", voivodeship: "Podlaskie"},
{city: "Dąbrowa Białostocka", voivodeship: "Podlaskie"},
{city: "Kolno", voivodeship: "Podlaskie"},
{city: "Lipsk", voivodeship: "Podlaskie"},
{city: "Jedwabne", voivodeship: "Podlaskie"},
{city: "Gdańsk", voivodeship: "Pomorskie"},
{city: "Gdynia", voivodeship: "Pomorskie"},
{city: "Słupsk", voivodeship: "Pomorskie"},
{city: "Tczew", voivodeship: "Pomorskie"},
{city: "Wejherowo", voivodeship: "Pomorskie"},
{city: "Starogard Gdański", voivodeship: "Pomorskie"},
{city: "Rumia", voivodeship: "Pomorskie"},
{city: "Kościerzyna", voivodeship: "Pomorskie"},
{city: "Lębork", voivodeship: "Pomorskie"},
{city: "Puck", voivodeship: "Pomorskie"},
{city: "Chojnice", voivodeship: "Pomorskie"},
{city: "Bytów", voivodeship: "Pomorskie"},
{city: "Sopot", voivodeship: "Pomorskie"},
{city: "Kwidzyn", voivodeship: "Pomorskie"},
{city: "Malbork", voivodeship: "Pomorskie"},
{city: "Reda", voivodeship: "Pomorskie"},
{city: "Władysławowo", voivodeship: "Pomorskie"},
{city: "Żukowo", voivodeship: "Pomorskie"},
{city: "Gniew", voivodeship: "Pomorskie"},
{city: "Pruszcz Gdański", voivodeship: "Pomorskie"},
{city: "Czersk", voivodeship: "Pomorskie"},
{city: "Człuchów", voivodeship: "Pomorskie"},
{city: "Sztum", voivodeship: "Pomorskie"},
{city: "Kartuzy", voivodeship: "Pomorskie"},
{city: "Nowy Dwór Gdański", voivodeship: "Pomorskie"},
{city: "Szczecin", voivodeship: "Zachodniopomorskie"},
{city: "Koszalin", voivodeship: "Zachodniopomorskie"},
{city: "Świnoujście", voivodeship: "Zachodniopomorskie"},
{city: "Stargard", voivodeship: "Zachodniopomorskie"},
{city: "Kołobrzeg", voivodeship: "Zachodniopomorskie"},
{city: "Police", voivodeship: "Zachodniopomorskie"},
{city: "Szczecinek", voivodeship: "Zachodniopomorskie"},
{city: "Świdwin", voivodeship: "Zachodniopomorskie"},
{city: "Gryfino", voivodeship: "Zachodniopomorskie"},
{city: "Goleniów", voivodeship: "Zachodniopomorskie"},
{city: "Drawsko Pomorskie", voivodeship: "Zachodniopomorskie"},
{city: "Łobez", voivodeship: "Zachodniopomorskie"},
{city: "Choszczno", voivodeship: "Zachodniopomorskie"},
{city: "Myślibórz", voivodeship: "Zachodniopomorskie"},
{city: "Węgorzyno", voivodeship: "Zachodniopomorskie"},
{city: "Dobrzany", voivodeship: "Zachodniopomorskie"},
{city: "Barlinek", voivodeship: "Zachodniopomorskie"},
{city: "Resko", voivodeship: "Zachodniopomorskie"},
{city: "Pyrzyce", voivodeship: "Zachodniopomorskie"},
{city: "Czaplinek", voivodeship: "Zachodniopomorskie"},
{city: "Białogard", voivodeship: "Zachodniopomorskie"},
{city: "Żukowo", voivodeship: "Zachodniopomorskie"},
{city: "Wolin", voivodeship: "Zachodniopomorskie"},
{city: "Sławno", voivodeship: "Zachodniopomorskie"},
{city: "Gorzów Wielkopolski", voivodeship: "Zachodniopomorskie"},
{city: "Słubice", voivodeship: "Zachodniopomorskie"},
{city: "Kostrzyn nad Odrą", voivodeship: "Zachodniopomorskie"},
{city: "Międzyrzecz", voivodeship: "Zachodniopomorskie"},
{city: "Nowe Warpno", voivodeship: "Zachodniopomorskie"},
{city: "Chojna", voivodeship: "Zachodniopomorskie"},
{city: "Mysłowice", voivodeship: "Zachodniopomorskie"},
{city: "Głogów", voivodeship: "Zachodniopomorskie"},
{city: "Zielona Góra", voivodeship: "Zachodniopomorskie"},
{city: "Świebodzin", voivodeship: "Zachodniopomorskie"},
{city: "Kargowa", voivodeship: "Zachodniopomorskie"},
{city: "Skwierzyna", voivodeship: "Zachodniopomorskie"},
{city: "Gryfice", voivodeship: "Zachodniopomorskie"},
{city: "Trzebiatów", voivodeship: "Zachodniopomorskie"},
{city: "Darłowo", voivodeship: "Zachodniopomorskie"},
{city: "Człopa", voivodeship: "Zachodniopomorskie"},
{city: "Drawno", voivodeship: "Zachodniopomorskie"},
{city: "Wałcz", voivodeship: "Zachodniopomorskie"},
{city: "Złocieniec", voivodeship: "Zachodniopomorskie"},
{city: "Chociwel", voivodeship: "Zachodniopomorskie"},
{city: "Lipiany", voivodeship: "Zachodniopomorskie"},
{city: "Pszczółki", voivodeship: "Pomorskie"},
{city: "Skarszewy", voivodeship: "Pomorskie"},
{city: "Nowy Staw", voivodeship: "Pomorskie"},
{city: "Katowice", voivodeship: "Śląskie"},
{city: "Zabrze", voivodeship: "Śląskie"},
{city: "Bytom", voivodeship: "Śląskie"},
{city: "Ruda Śląska", voivodeship: "Śląskie"},
{city: "Tychy", voivodeship: "Śląskie"},
{city: "Chorzów", voivodeship: "Śląskie"},
{city: "Jaworzno", voivodeship: "Śląskie"},
{city: "Rybnik", voivodeship: "Śląskie"},
{city: "Zawiercie", voivodeship: "Śląskie"},
{city: "Mysłowice", voivodeship: "Śląskie"},
{city: "Siemianowice Śląskie", voivodeship: "Śląskie"},
{city: "Żory", voivodeship: "Śląskie"},
{city: "Knurów", voivodeship: "Śląskie"},
{city: "Gliwice", voivodeship: "Śląskie"},
{city: "Mikołów", voivodeship: "Śląskie"},
{city: "Częstochowa", voivodeship: "Śląskie"},
{city: "Tarnowskie Góry", voivodeship: "Śląskie"},
{city: "Piekary Śląskie", voivodeship: "Śląskie"},
{city: "Radzionków", voivodeship: "Śląskie"},
{city: "Wodzisław Śląski", voivodeship: "Śląskie"},
{city: "Pyskowice", voivodeship: "Śląskie"},
{city: "Pszczyna", voivodeship: "Śląskie"},
{city: "Czerwionka-Leszczyny", voivodeship: "Śląskie"},
{city: "Orzesze", voivodeship: "Śląskie"},
{city: "Łaziska Górne", voivodeship: "Śląskie"},
{city: "Będzin", voivodeship: "Śląskie"},
{city: "Sosnowiec", voivodeship: "Śląskie"},
{city: "Siewierz", voivodeship: "Śląskie"},
{city: "Myszków", voivodeship: "Śląskie"},
{city: "Gierałtowice", voivodeship: "Śląskie"},
{city: "Zabierzów", voivodeship: "Śląskie"},
{city: "Pszów", voivodeship: "Śląskie"},
{city: "Sławków", voivodeship: "Śląskie"},
{city: "Pilchowice", voivodeship: "Śląskie"},
{city: "Świętochłowice", voivodeship: "Śląskie"},
{city: "Lędziny", voivodeship: "Śląskie"},
{city: "Imielin", voivodeship: "Śląskie"},
{city: "Jastrzębie-Zdrój", voivodeship: "Śląskie"},
{city: "Miasteczko Śląskie", voivodeship: "Śląskie"},
{city: "Dąbrowa Górnicza", voivodeship: "Śląskie"},
{city: "Kielce", voivodeship: "Świętokrzyskie"},
{city: "Ostrowiec Świętokrzyski", voivodeship: "Świętokrzyskie"},
{city: "Starachowice", voivodeship: "Świętokrzyskie"},
{city: "Sandomierz", voivodeship: "Świętokrzyskie"},
{city: "Skarżysko-Kamienna", voivodeship: "Świętokrzyskie"},
{city: "Końskie", voivodeship: "Świętokrzyskie"},
{city: "Staszów", voivodeship: "Świętokrzyskie"},
{city: "Busko-Zdrój", voivodeship: "Świętokrzyskie"},
{city: "Kazimierza Wielka", voivodeship: "Świętokrzyskie"},
{city: "Pińczów", voivodeship: "Świętokrzyskie"},
{city: "Opatów", voivodeship: "Świętokrzyskie"},
{city: "Stopnica", voivodeship: "Świętokrzyskie"},
{city: "Oleśnica", voivodeship: "Świętokrzyskie"},
{city: "Nowy Korczyn", voivodeship: "Świętokrzyskie"},
{city: "Ożarów", voivodeship: "Świętokrzyskie"},
{city: "Kunów", voivodeship: "Świętokrzyskie"},
{city: "Jędrzejów", voivodeship: "Świętokrzyskie"},
{city: "Chęciny", voivodeship: "Świętokrzyskie"},
{city: "Pacanów", voivodeship: "Świętokrzyskie"},
{city: "Działoszyce", voivodeship: "Świętokrzyskie"},
{city: "Koprzywnica", voivodeship: "Świętokrzyskie"},
{city: "Sędziszów", voivodeship: "Świętokrzyskie"},
{city: "Bodzentyn", voivodeship: "Świętokrzyskie"},
{city: "Mniów", voivodeship: "Świętokrzyskie"},
{city: "Jedrzejów", voivodeship: "Świętokrzyskie"},
{city: "Piekoszów", voivodeship: "Świętokrzyskie"},
{city: "Konskie", voivodeship: "Świętokrzyskie"},
{city: "Daleszyce", voivodeship: "Świętokrzyskie"},
{city: "Chmielnik", voivodeship: "Świętokrzyskie"},
{city: "Łagów", voivodeship: "Świętokrzyskie"},
{city: "Szydłów", voivodeship: "Świętokrzyskie"},
{city: "Zagnańsk", voivodeship: "Świętokrzyskie"},
{city: "Włoszczowa", voivodeship: "Świętokrzyskie"},
{city: "Suchedniów", voivodeship: "Świętokrzyskie"},
{city: "Bliżyn", voivodeship: "Świętokrzyskie"},
{city: "Gowarczów", voivodeship: "Świętokrzyskie"},
{city: "Nowa Słupia", voivodeship: "Świętokrzyskie"},
{city: "Mirzec", voivodeship: "Świętokrzyskie"},
{city: "Olsztyn", voivodeship: "Warmińsko-Mazurskie"},
{city: "Elbląg", voivodeship: "Warmińsko-Mazurskie"},
{city: "Ełk", voivodeship: "Warmińsko-Mazurskie"},
{city: "Ostróda", voivodeship: "Warmińsko-Mazurskie"},
{city: "Giżycko", voivodeship: "Warmińsko-Mazurskie"},
{city: "Iława", voivodeship: "Warmińsko-Mazurskie"},
{city: "Bartoszyce", voivodeship: "Warmińsko-Mazurskie"},
{city: "Kętrzyn", voivodeship: "Warmińsko-Mazurskie"},
{city: "Działdowo", voivodeship: "Warmińsko-Mazurskie"},
{city: "Mrągowo", voivodeship: "Warmińsko-Mazurskie"},
{city: "Szczytno", voivodeship: "Warmińsko-Mazurskie"},
{city: "Pisz", voivodeship: "Warmińsko-Mazurskie"},
{city: "Reszel", voivodeship: "Warmińsko-Mazurskie"},
{city: "Pasym", voivodeship: "Warmińsko-Mazurskie"},
{city: "Nidzica", voivodeship: "Warmińsko-Mazurskie"},
{city: "Biskupiec", voivodeship: "Warmińsko-Mazurskie"},
{city: "Olsztynek", voivodeship: "Warmińsko-Mazurskie"},
{city: "Dobre Miasto", voivodeship: "Warmińsko-Mazurskie"},
{city: "Orneta", voivodeship: "Warmińsko-Mazurskie"},
{city: "Morąg", voivodeship: "Warmińsko-Mazurskie"},
{city: "Lidzbark Warmiński", voivodeship: "Warmińsko-Mazurskie"},
{city: "Korsze", voivodeship: "Warmińsko-Mazurskie"},
{city: "Nowe Miasto Lubawskie", voivodeship: "Warmińsko-Mazurskie"},
{city: "Miłomłyn", voivodeship: "Warmińsko-Mazurskie"},
{city: "Mława", voivodeship: "Warmińsko-Mazurskie"},
{city: "Węgorzewo", voivodeship: "Warmińsko-Mazurskie"},
{city: "Braniewo", voivodeship: "Warmińsko-Mazurskie"},
{city: "Golub-Dobrzyń", voivodeship: "Warmińsko-Mazurskie"},
{city: "Ryn", voivodeship: "Warmińsko-Mazurskie"},
{city: "Susz", voivodeship: "Warmińsko-Mazurskie"},
{city: "Kisielice", voivodeship: "Warmińsko-Mazurskie"},
{city: "Miłakowo", voivodeship: "Warmińsko-Mazurskie"},
{city: "Barczewo", voivodeship: "Warmińsko-Mazurskie"},
{city: "Biała Piska", voivodeship: "Warmińsko-Mazurskie"},
{city: "Ruciane-Nida", voivodeship: "Warmińsko-Mazurskie"},
{city: "Kowalewo Pomorskie", voivodeship: "Warmińsko-Mazurskie"},
{city: "Jeziorany", voivodeship: "Warmińsko-Mazurskie"},
{city: "Poznań", voivodeship: "Wielkopolskie"},
{city: "Kalisz", voivodeship: "Wielkopolskie"},
{city: "Konin", voivodeship: "Wielkopolskie"},
{city: "Pleszew", voivodeship: "Wielkopolskie"},
{city: "Ostrów Wielkopolski", voivodeship: "Wielkopolskie"},
{city: "Gniezno", voivodeship: "Wielkopolskie"},
{city: "Środa Wielkopolska", voivodeship: "Wielkopolskie"},
{city: "Krotoszyn", voivodeship: "Wielkopolskie"},
{city: "Rawicz", voivodeship: "Wielkopolskie"},
{city: "Leszno", voivodeship: "Wielkopolskie"},
{city: "Kościan", voivodeship: "Wielkopolskie"},
{city: "Gostyń", voivodeship: "Wielkopolskie"},
{city: "Jarocin", voivodeship: "Wielkopolskie"},
{city: "Września", voivodeship: "Wielkopolskie"},
{city: "Śrem", voivodeship: "Wielkopolskie"},
{city: "Wągrowiec", voivodeship: "Wielkopolskie"},
{city: "Kępno", voivodeship: "Wielkopolskie"},
{city: "Trzcianka", voivodeship: "Wielkopolskie"},
{city: "Pniewy", voivodeship: "Wielkopolskie"},
{city: "Żnin", voivodeship: "Wielkopolskie"},
{city: "Oborniki", voivodeship: "Wielkopolskie"},
{city: "Międzychód", voivodeship: "Wielkopolskie"},
{city: "Nowy Tomyśl", voivodeship: "Wielkopolskie"},
{city: "Wolsztyn", voivodeship: "Wielkopolskie"},
{city: "Czarnków", voivodeship: "Wielkopolskie"},
{city: "Swarzędz", voivodeship: "Wielkopolskie"},
{city: "Koło", voivodeship: "Wielkopolskie"},
{city: "Szamotuły", voivodeship: "Wielkopolskie"},
{city: "Wronki", voivodeship: "Wielkopolskie"},
{city: "Luboń", voivodeship: "Wielkopolskie"},
{city: "Ślesin", voivodeship: "Wielkopolskie"},
{city: "Mosina", voivodeship: "Wielkopolskie"},
{city: "Śmigiel", voivodeship: "Wielkopolskie"},
{city: "Słupca", voivodeship: "Wielkopolskie"},
{city: "Turek", voivodeship: "Wielkopolskie"},
{city: "Zielona Góra", voivodeship: "Lubuskie"},
{city: "Gorzów Wielkopolski", voivodeship: "Lubuskie"},
{city: "Nowa Sól", voivodeship: "Lubuskie"},
{city: "Świebodzin", voivodeship: "Lubuskie"},
{city: "Zary", voivodeship: "Lubuskie"},
{city: "Żagań", voivodeship: "Lubuskie"},
{city: "Kostrzyn nad Odrą", voivodeship: "Lubuskie"},
{city: "Słubice", voivodeship: "Lubuskie"},
{city: "Krosno Odrzańskie", voivodeship: "Lubuskie"},
{city: "Międzyrzecz", voivodeship: "Lubuskie"},
{city: "Gubin", voivodeship: "Lubuskie"},
{city: "Sulechów", voivodeship: "Lubuskie"},
{city: "Strzelce Krajeńskie", voivodeship: "Lubuskie"},
{city: "Lubsko", voivodeship: "Lubuskie"},
{city: "Sława", voivodeship: "Lubuskie"},
{city: "Żary", voivodeship: "Lubuskie"},
{city: "Kożuchów", voivodeship: "Lubuskie"},
{city: "Skwierzyna", voivodeship: "Lubuskie"},
{city: "Wschowa", voivodeship: "Lubuskie"},
{city: "Szprotawa", voivodeship: "Lubuskie"},
{city: "Sulechów", voivodeship: "Lubuskie"}
]
